"""initial schema

Revision ID: b8e53f42f1e8
Revises: 
Create Date: 2026-09-11 12:52:26.775405

"""
from alembic import op
import sqlalchemy as sa


revision = 'b8e53f42f1e8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contest', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contest_id'), ['id'], unique=False)

    op.create_table('couloirtype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('couloirtype', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_couloirtype_id'), ['id'], unique=False)

    op.create_table('crenautype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crenautype', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crenautype_id'), ['id'], unique=False)

    op.create_table('subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscription_id'), ['id'], unique=False)

    op.create_table('usergroup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('usergroup', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usergroup_id'), ['id'], unique=False)

    op.create_table('userrole',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('userrole', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_userrole_id'), ['id'], unique=False)

    op.create_table('userstatus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('userstatus', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_userstatus_id'), ['id'], unique=False)

    op.create_table('versionvoie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('parent_version_id', sa.Integer(), nullable=True),
    sa.Column('subversion', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_version_id'], ['versionvoie.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('versionvoie', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_versionvoie_id'), ['id'], unique=False)

    op.create_table('couloir',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['couloirtype.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('couloir', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_couloir_id'), ['id'], unique=False)

    op.create_table('crenau',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=True),
    sa.Column('cron', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['type_id'], ['crenautype.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crenau', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crenau_id'), ['id'], unique=False)

    op.create_table('seance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start', sa.DateTime(), nullable=True),
    sa.Column('end', sa.DateTime(), nullable=True),
    sa.Column('max_people', sa.Integer(), nullable=True),
    sa.Column('subscription_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscription.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('seance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_seance_id'), ['id'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('surname', sa.String(), nullable=True),
    sa.Column('pwd_hash', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('subscription_id', sa.Integer(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['usergroup.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['userrole.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['userstatus.id'], ),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscription.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_id'), ['id'], unique=False)

    op.create_table('usercontest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contest_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('score_voie', sa.Integer(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contest_id'], ['contest.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usercontest', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usercontest_id'), ['id'], unique=False)

    op.create_table('zonecontest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contest_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['contest_id'], ['contest.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('zonecontest', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_zonecontest_id'), ['id'], unique=False)

    op.create_table('bloccontest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contest_id', sa.Integer(), nullable=True),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('top', sa.Integer(), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contest_id'], ['contest.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zonecontest.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bloccontest', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bloccontest_id'), ['id'], unique=False)

    op.create_table('seancesubscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seance_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['seance_id'], ['seance.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('seancesubscription', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_seancesubscription_id'), ['id'], unique=False)

    op.create_table('speedresultcontest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contest_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('time', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['contest_id'], ['contest.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['usercontest.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('speedresultcontest', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_speedresultcontest_id'), ['id'], unique=False)

    op.create_table('voie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('couloir_id', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('difficulty', sa.Float(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('versionvoie_id', sa.Integer(), nullable=True),
    sa.Column('source_voie_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['couloir_id'], ['couloir.id'], ),
    sa.ForeignKeyConstraint(['source_voie_id'], ['voie.id'], ),
    sa.ForeignKeyConstraint(['versionvoie_id'], ['versionvoie.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('voie', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_voie_id'), ['id'], unique=False)

    op.create_table('voiecontest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contest_id', sa.Integer(), nullable=True),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('top', sa.Integer(), nullable=True),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contest_id'], ['contest.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zonecontest.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('voiecontest', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_voiecontest_id'), ['id'], unique=False)

    op.create_table('resultcontest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contest_id', sa.Integer(), nullable=True),
    sa.Column('bloc_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bloc_id'], ['bloccontest.id'], ),
    sa.ForeignKeyConstraint(['contest_id'], ['contest.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['usercontest.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resultcontest', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resultcontest_id'), ['id'], unique=False)

    op.create_table('resultcontestvoie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contest_id', sa.Integer(), nullable=True),
    sa.Column('voie_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contest_id'], ['contest.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['usercontest.id'], ),
    sa.ForeignKeyConstraint(['voie_id'], ['voiecontest.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('resultcontestvoie', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_resultcontestvoie_id'), ['id'], unique=False)

    op.create_table('userseance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('voie_id', sa.Integer(), nullable=True),
    sa.Column('en_tete', sa.Boolean(), nullable=True),
    sa.Column('top', sa.Integer(), nullable=True),
    sa.Column('pause', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['voie_id'], ['voie.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('userseance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_userseance_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('userseance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_userseance_id'))

    op.drop_table('userseance')
    with op.batch_alter_table('resultcontestvoie', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resultcontestvoie_id'))

    op.drop_table('resultcontestvoie')
    with op.batch_alter_table('resultcontest', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_resultcontest_id'))

    op.drop_table('resultcontest')
    with op.batch_alter_table('voiecontest', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_voiecontest_id'))

    op.drop_table('voiecontest')
    with op.batch_alter_table('voie', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_voie_id'))

    op.drop_table('voie')
    with op.batch_alter_table('speedresultcontest', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_speedresultcontest_id'))

    op.drop_table('speedresultcontest')
    with op.batch_alter_table('seancesubscription', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_seancesubscription_id'))

    op.drop_table('seancesubscription')
    with op.batch_alter_table('bloccontest', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bloccontest_id'))

    op.drop_table('bloccontest')
    with op.batch_alter_table('zonecontest', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_zonecontest_id'))

    op.drop_table('zonecontest')
    with op.batch_alter_table('usercontest', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usercontest_id'))

    op.drop_table('usercontest')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_id'))

    op.drop_table('user')
    with op.batch_alter_table('seance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_seance_id'))

    op.drop_table('seance')
    with op.batch_alter_table('crenau', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crenau_id'))

    op.drop_table('crenau')
    with op.batch_alter_table('couloir', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_couloir_id'))

    op.drop_table('couloir')
    with op.batch_alter_table('versionvoie', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_versionvoie_id'))

    op.drop_table('versionvoie')
    with op.batch_alter_table('userstatus', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_userstatus_id'))

    op.drop_table('userstatus')
    with op.batch_alter_table('userrole', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_userrole_id'))

    op.drop_table('userrole')
    with op.batch_alter_table('usergroup', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usergroup_id'))

    op.drop_table('usergroup')
    with op.batch_alter_table('subscription', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscription_id'))

    op.drop_table('subscription')
    with op.batch_alter_table('crenautype', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crenautype_id'))

    op.drop_table('crenautype')
    with op.batch_alter_table('couloirtype', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_couloirtype_id'))

    op.drop_table('couloirtype')
    with op.batch_alter_table('contest', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contest_id'))

    op.drop_table('contest')
    # ### end Alembic commands ###
